### ISSUE TITLE
Can I make some translation?

### ISSUE THREAD

**Issue by fairjm** [Darksonn/ryhl.io#2]
Sorry for asking after doing the translation 😂. It's my bad.  
Before I read the article [Async: What is blocking?](https://ryhl.io/blog/async-what-is-blocking/) and think it is really awesome and easy understanding.  
So I translated it to Chinese and put it into my repo and github pages. [here](https://github.com/fairjm/blog_posts/blob/master/translation-async-what-is-blocking.md) and [here](https://bingowith.me/2021/05/09/translation-async-what-is-blocking/).  
I keep the original url at the begin and the end of the translation.  
If you don't like this I will delete it as soon as you tell me.  
sry for bothering. :)

**Comment by Darksonn** [comment]
Thanks! I would be happy to include a link to the translation. What text should I use for the link?

**Comment by fairjm** [comment]
Thank you :)
The title in chinese is 'async: 什么是blocking'  
maybe just named 'chinese version' is enough

**Comment by Darksonn** [comment]
Hey, sorry I forgot to put in the link. It should be there now. Thanks for the translation :)

**Comment by Darksonn** [comment]
Be aware that you have some links to Tokio version 0.3, but my article has been updated so the links go to Tokio version 1.x.y instead.
